# @package _group_
# _target_: models.video_classification.TIMMModel
_target_: models.video_classification_time_shift.TIMMModelTS
# _target_: models.video_classification_time_shift.TIMMModelSwin
model_type: vit_base_patch8_224
