# @package _group_._name_
is_train: false
_target_: datasets.epic_kitchens.EPICKitchens
root: ${dataset.epic_kitchens.common.data_dir}/train
return_future_clips_too: ${dataset.epic_kitchens.common.return_future_clips_too}
annotation_path:
  - ${dataset.epic_kitchens.common.annot_dir}/EPIC_train_action_labels.pkl
annotation_dir: ${dataset.epic_kitchens.common.annot_dir}
# embeddings_path: ${cwd}/encodings_epic55.pth
# similarities_path: ${cwd}/similarities_epic55.pth
embeddings_path: ${dataset.epic_kitchens.common.embeddings_path}
similarities_path: ${dataset.epic_kitchens.common.similarities_path}
visual_encodings_path: ${dataset.epic_kitchens.common.embeddings_path}
label_type: ${dataset.epic_kitchens.common.label_type}
tubelets: ${dataset.epic_kitchens.common.tubelets}
sample_strategy: "random_clip"
# https://github.com/fpv-iplab/rulstm/blob/master/RULSTM/data/training_videos.csv
action_labels_fpath: ${dataset.epic_kitchens.common.rulstm_annot_dir}/actions.csv
reader_fn:  # Setting it since for EGTEA I mostly use RULSTM features
  _target_: 
    - datasets.reader_fns.DefaultReader
    # - datasets.epic_kitchens.EpicRULSTMFeatsReader
  # lmdb_path:
    # - ${dataset.epic_kitchens.common.rulstm_feats_dir}/flow
    # - ${dataset.epic_kitchens.common.rulstm_feats_dir}/igm65m
    # - ${dataset.epic_kitchens.common.rulstm_feats_dir}/rgb
    # - ${dataset.epic_kitchens.common.rulstm_feats_dir}/obj
  # read_type: normal
  # warn_if_using_closeby_frame: false
conv_to_anticipate_fn:
  _target_: datasets.base_video_dataset.convert_to_anticipation
  tau_a: ${dataset.epic_kitchens.common.tau_a}
  tau_o: ${dataset.epic_kitchens.common.tau_o}
