# @package _group_._name_

_target_: datasets.breakfast_50salads.Breakfast50Salads
which: 50Salads
root: ${dataset.dundee50salads.common.videos_dir}
splits_dir: ${dataset.dundee50salads.common.splits_dir}
classes_fpath: ${dataset.dundee50salads.common.classes_fpath}
is_train: true
fold: ${dataset.dundee50salads.common.fold}
tubelets: ${dataset.dundee50salads.common.tubelets}
sample_strategy: last_clip
annot_reader_fn: ${dataset.dundee50salads.annot_reader_fn}
embeddings_path: ${cwd}/encodings_50salads.pth
similarities_path: ${cwd}/similarities_50salads.pth
visual_encodings_path: ${cwd}/encodings_50salads.pth
conv_to_anticipate_fn:
  _target_: datasets.base_video_dataset.convert_to_anticipation
  tau_a: 1.0
  tau_o: 2.5
